runtime: python37

service: lab2v1

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
 
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /api1/v1/tvs.*
  script: auto